runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F2

env_variables:
 BUCKET_NAME: "megas-tool-1"

handlers:
- url: /megas-client-0.3
  static_dir: megas-client-0.3

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
